version: "3"

tasks:
  format:
    cmds:
      - autopep8 --in-place --recursive day_*

  test:
    cmds:
      - pytest -s -v

  day1:
    dir: day_01
    cmds:
      - python day_01.py

  day2:
    dir: day_02
    cmds:
      - python day_02.py
