version: "3"

tasks:
  format:
    cmds:
      - autopep8 --in-place --recursive day_*

  test:
    cmds:
      - pytest -s -v

  day1:
    dir: day_01
    cmds:
      - python day_01.py

  day2:
    dir: day_02
    cmds:
      - python day_02.py

  day3:
    dir: day_03
    cmds:
      - python day_03.py

  day4:
    dir: day_04
    cmds:
      - python day_04.py

  day5:
    dir: day_05
    cmds:
      - python day_05.py

  day6:
    dir: day_06
    cmds:
      - python day_06.py

  day7:
    dir: day_07
    cmds:
      - python day_07.py

  day8:
    dir: day_08
    cmds:
      - python day_08.py

  day9:
    dir: day_09
    cmds:
      - python day_09.py

  day10:
    dir: day_10
    cmds:
      - python day_10.py

  day11:
    dir: day_11
    cmds:
      - python day_11.py

  day12:
    dir: day_12
    cmds:
      - python day_12.py
