version: "3"

tasks:
  format:
    cmds:
      - autopep8 --in-place --recursive day_*
      - add-trailing-comma day_*/*.py
      - reorder-python-imports day_*/*.py

  test:
    cmds:
      - pytest -s -v

  day1:
    dir: day_01
    cmds:
      - python3 day_01.py

  day2:
    dir: day_02
    cmds:
      - python3 day_02.py

  day3:
    dir: day_03
    cmds:
      - python3 day_03.py

  day4:
    dir: day_04
    cmds:
      - python3 day_04.py

  day5:
    dir: day_05
    cmds:
      - python3 day_05.py

  day6:
    dir: day_06
    cmds:
      - python3 day_06.py

  day7:
    dir: day_07
    cmds:
      - python3 day_07.py

  day8:
    dir: day_08
    cmds:
      - python3 day_08.py

  day9:
    dir: day_09
    cmds:
      - python3 day_09.py

  day10:
    dir: day_10
    cmds:
      - python3 day_10.py

  day11:
    dir: day_11
    cmds:
      - python3 day_11.py

  day12:
    dir: day_12
    cmds:
      - python3 day_12.py

  day13:
    dir: day_13
    cmds:
      - python3 day_13.py

  day14:
    dir: day_14
    cmds:
      - python3 day_14.py

  day15:
    dir: day_15
    cmds:
      - python3 day_15.py

  day16:
    dir: day_16
    cmds:
      - python3 day_16.py

  day17:
    dir: day_17
    cmds:
      - python3 day_17.py
